// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package searxng

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Answer) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Answer":
			z.Answer, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Answer")
				return
			}
		case "Template":
			z.Template, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Engine":
			z.Engine, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Position":
			z.Position, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Position")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Answer) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Answer"
	err = en.Append(0x85, 0xa6, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Answer)
	if err != nil {
		err = msgp.WrapError(err, "Answer")
		return
	}
	// write "Template"
	err = en.Append(0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Template)
	if err != nil {
		err = msgp.WrapError(err, "Template")
		return
	}
	// write "Engine"
	err = en.Append(0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Engine)
	if err != nil {
		err = msgp.WrapError(err, "Engine")
		return
	}
	// write "URL"
	err = en.Append(0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "Position"
	err = en.Append(0xa8, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Position)
	if err != nil {
		err = msgp.WrapError(err, "Position")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Answer) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Answer"
	o = append(o, 0x85, 0xa6, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72)
	o = msgp.AppendString(o, z.Answer)
	// string "Template"
	o = append(o, 0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.Template)
	// string "Engine"
	o = append(o, 0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	o = msgp.AppendString(o, z.Engine)
	// string "URL"
	o = append(o, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	// string "Position"
	o = append(o, 0xa8, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt(o, z.Position)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Answer) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Answer":
			z.Answer, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Answer")
				return
			}
		case "Template":
			z.Template, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Engine":
			z.Engine, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Position":
			z.Position, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Position")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Answer) Msgsize() (s int) {
	s = 1 + 7 + msgp.StringPrefixSize + len(z.Answer) + 9 + msgp.StringPrefixSize + len(z.Template) + 7 + msgp.StringPrefixSize + len(z.Engine) + 4 + msgp.StringPrefixSize + len(z.URL) + 9 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EngineError) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(EngineError, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z EngineError) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		err = en.WriteString(z[zb0003])
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z EngineError) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		o = msgp.AppendString(o, z[zb0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EngineError) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(EngineError, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z EngineError) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		s += msgp.StringPrefixSize + len(z[zb0003])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Infobox) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Infobox":
			z.Infobox, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Infobox")
				return
			}
		case "Template":
			z.Template, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Engine":
			z.Engine, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "ImgSrc":
			z.ImgSrc, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ImgSrc")
				return
			}
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "URLs":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "URLs")
				return
			}
			if cap(z.URLs) >= int(zb0002) {
				z.URLs = (z.URLs)[:zb0002]
			} else {
				z.URLs = make([]InfoboxURL, zb0002)
			}
			for za0001 := range z.URLs {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "URLs", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "URLs", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Title":
						z.URLs[za0001].Title, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0001, "Title")
							return
						}
					case "URL":
						z.URLs[za0001].URL, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0001, "URL")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0001)
							return
						}
					}
				}
			}
		case "Attributes":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Attributes")
				return
			}
			if cap(z.Attributes) >= int(zb0004) {
				z.Attributes = (z.Attributes)[:zb0004]
			} else {
				z.Attributes = make([]InfoboxAttribute, zb0004)
			}
			for za0002 := range z.Attributes {
				err = z.Attributes[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Attributes", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Infobox) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "Infobox"
	err = en.Append(0x88, 0xa7, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x78)
	if err != nil {
		return
	}
	err = en.WriteString(z.Infobox)
	if err != nil {
		err = msgp.WrapError(err, "Infobox")
		return
	}
	// write "Template"
	err = en.Append(0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Template)
	if err != nil {
		err = msgp.WrapError(err, "Template")
		return
	}
	// write "Engine"
	err = en.Append(0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Engine)
	if err != nil {
		err = msgp.WrapError(err, "Engine")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "ImgSrc"
	err = en.Append(0xa6, 0x49, 0x6d, 0x67, 0x53, 0x72, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.ImgSrc)
	if err != nil {
		err = msgp.WrapError(err, "ImgSrc")
		return
	}
	// write "ID"
	err = en.Append(0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "URLs"
	err = en.Append(0xa4, 0x55, 0x52, 0x4c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.URLs)))
	if err != nil {
		err = msgp.WrapError(err, "URLs")
		return
	}
	for za0001 := range z.URLs {
		// map header, size 2
		// write "Title"
		err = en.Append(0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.URLs[za0001].Title)
		if err != nil {
			err = msgp.WrapError(err, "URLs", za0001, "Title")
			return
		}
		// write "URL"
		err = en.Append(0xa3, 0x55, 0x52, 0x4c)
		if err != nil {
			return
		}
		err = en.WriteString(z.URLs[za0001].URL)
		if err != nil {
			err = msgp.WrapError(err, "URLs", za0001, "URL")
			return
		}
	}
	// write "Attributes"
	err = en.Append(0xaa, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Attributes)))
	if err != nil {
		err = msgp.WrapError(err, "Attributes")
		return
	}
	for za0002 := range z.Attributes {
		err = z.Attributes[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Attributes", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Infobox) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "Infobox"
	o = append(o, 0x88, 0xa7, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x78)
	o = msgp.AppendString(o, z.Infobox)
	// string "Template"
	o = append(o, 0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.Template)
	// string "Engine"
	o = append(o, 0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	o = msgp.AppendString(o, z.Engine)
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "ImgSrc"
	o = append(o, 0xa6, 0x49, 0x6d, 0x67, 0x53, 0x72, 0x63)
	o = msgp.AppendString(o, z.ImgSrc)
	// string "ID"
	o = append(o, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "URLs"
	o = append(o, 0xa4, 0x55, 0x52, 0x4c, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.URLs)))
	for za0001 := range z.URLs {
		// map header, size 2
		// string "Title"
		o = append(o, 0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
		o = msgp.AppendString(o, z.URLs[za0001].Title)
		// string "URL"
		o = append(o, 0xa3, 0x55, 0x52, 0x4c)
		o = msgp.AppendString(o, z.URLs[za0001].URL)
	}
	// string "Attributes"
	o = append(o, 0xaa, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Attributes)))
	for za0002 := range z.Attributes {
		o, err = z.Attributes[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Attributes", za0002)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Infobox) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Infobox":
			z.Infobox, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Infobox")
				return
			}
		case "Template":
			z.Template, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Engine":
			z.Engine, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "ImgSrc":
			z.ImgSrc, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ImgSrc")
				return
			}
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "URLs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URLs")
				return
			}
			if cap(z.URLs) >= int(zb0002) {
				z.URLs = (z.URLs)[:zb0002]
			} else {
				z.URLs = make([]InfoboxURL, zb0002)
			}
			for za0001 := range z.URLs {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "URLs", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "URLs", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Title":
						z.URLs[za0001].Title, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0001, "Title")
							return
						}
					case "URL":
						z.URLs[za0001].URL, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0001, "URL")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0001)
							return
						}
					}
				}
			}
		case "Attributes":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Attributes")
				return
			}
			if cap(z.Attributes) >= int(zb0004) {
				z.Attributes = (z.Attributes)[:zb0004]
			} else {
				z.Attributes = make([]InfoboxAttribute, zb0004)
			}
			for za0002 := range z.Attributes {
				bts, err = z.Attributes[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Attributes", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Infobox) Msgsize() (s int) {
	s = 1 + 8 + msgp.StringPrefixSize + len(z.Infobox) + 9 + msgp.StringPrefixSize + len(z.Template) + 7 + msgp.StringPrefixSize + len(z.Engine) + 8 + msgp.StringPrefixSize + len(z.Content) + 7 + msgp.StringPrefixSize + len(z.ImgSrc) + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.URLs {
		s += 1 + 6 + msgp.StringPrefixSize + len(z.URLs[za0001].Title) + 4 + msgp.StringPrefixSize + len(z.URLs[za0001].URL)
	}
	s += 11 + msgp.ArrayHeaderSize
	for za0002 := range z.Attributes {
		s += z.Attributes[za0002].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *InfoboxAttribute) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Label":
			z.Label, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Label")
				return
			}
		case "Value":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "Image":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Image")
				return
			}
			if z.Image == nil {
				z.Image = make(map[string]string, zb0002)
			} else if len(z.Image) > 0 {
				clear(z.Image)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Image")
					return
				}
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Image", za0001)
					return
				}
				z.Image[za0001] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *InfoboxAttribute) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Label"
	err = en.Append(0x83, 0xa5, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Label)
	if err != nil {
		err = msgp.WrapError(err, "Label")
		return
	}
	// write "Value"
	err = en.Append(0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	// write "Image"
	err = en.Append(0xa5, 0x49, 0x6d, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Image)))
	if err != nil {
		err = msgp.WrapError(err, "Image")
		return
	}
	for za0001, za0002 := range z.Image {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Image")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Image", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *InfoboxAttribute) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Label"
	o = append(o, 0x83, 0xa5, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	o = msgp.AppendString(o, z.Label)
	// string "Value"
	o = append(o, 0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	o = msgp.AppendString(o, z.Value)
	// string "Image"
	o = append(o, 0xa5, 0x49, 0x6d, 0x61, 0x67, 0x65)
	o = msgp.AppendMapHeader(o, uint32(len(z.Image)))
	for za0001, za0002 := range z.Image {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *InfoboxAttribute) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Label":
			z.Label, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Label")
				return
			}
		case "Value":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "Image":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Image")
				return
			}
			if z.Image == nil {
				z.Image = make(map[string]string, zb0002)
			} else if len(z.Image) > 0 {
				clear(z.Image)
			}
			for zb0002 > 0 {
				var za0002 string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Image")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Image", za0001)
					return
				}
				z.Image[za0001] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *InfoboxAttribute) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Label) + 6 + msgp.StringPrefixSize + len(z.Value) + 6 + msgp.MapHeaderSize
	if z.Image != nil {
		for za0001, za0002 := range z.Image {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *InfoboxURL) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z InfoboxURL) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Title"
	err = en.Append(0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "URL"
	err = en.Append(0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z InfoboxURL) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Title"
	o = append(o, 0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "URL"
	o = append(o, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *InfoboxURL) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z InfoboxURL) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Title) + 4 + msgp.StringPrefixSize + len(z.URL)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *LegacyResult) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Template":
			z.Template, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Engine":
			z.Engine, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "ParsedURL":
			z.ParsedURL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ParsedURL")
				return
			}
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "ImgSrc":
			z.ImgSrc, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ImgSrc")
				return
			}
		case "Thumbnail":
			z.Thumbnail, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Thumbnail")
				return
			}
		case "Priority":
			z.Priority, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Priority")
				return
			}
		case "Engines":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Engines")
				return
			}
			if cap(z.Engines) >= int(zb0002) {
				z.Engines = (z.Engines)[:zb0002]
			} else {
				z.Engines = make([]string, zb0002)
			}
			for za0001 := range z.Engines {
				z.Engines[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Engines", za0001)
					return
				}
			}
		case "Positions":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Positions")
				return
			}
			if cap(z.Positions) >= int(zb0003) {
				z.Positions = (z.Positions)[:zb0003]
			} else {
				z.Positions = make([]int, zb0003)
			}
			for za0002 := range z.Positions {
				z.Positions[za0002], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Positions", za0002)
					return
				}
			}
		case "Score":
			z.Score, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Score")
				return
			}
		case "Category":
			z.Category, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Category")
				return
			}
		case "PublishedDate":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "PublishedDate")
					return
				}
				z.PublishedDate = nil
			} else {
				if z.PublishedDate == nil {
					z.PublishedDate = new(Time)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "PublishedDate")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "PublishedDate")
						return
					}
					switch msgp.UnsafeString(field) {
					case "Time":
						z.PublishedDate.Time, err = dc.ReadTime()
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate", "Time")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate")
							return
						}
					}
				}
			}
		case "PubDate":
			z.PubDate, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PubDate")
				return
			}
		case "URLs":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "URLs")
				return
			}
			if cap(z.URLs) >= int(zb0005) {
				z.URLs = (z.URLs)[:zb0005]
			} else {
				z.URLs = make([]InfoboxURL, zb0005)
			}
			for za0003 := range z.URLs {
				var zb0006 uint32
				zb0006, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "URLs", za0003)
					return
				}
				for zb0006 > 0 {
					zb0006--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "URLs", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Title":
						z.URLs[za0003].Title, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0003, "Title")
							return
						}
					case "URL":
						z.URLs[za0003].URL, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0003, "URL")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0003)
							return
						}
					}
				}
			}
		case "Attributes":
			var zb0007 uint32
			zb0007, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Attributes")
				return
			}
			if cap(z.Attributes) >= int(zb0007) {
				z.Attributes = (z.Attributes)[:zb0007]
			} else {
				z.Attributes = make([]InfoboxAttribute, zb0007)
			}
			for za0004 := range z.Attributes {
				err = z.Attributes[za0004].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Attributes", za0004)
					return
				}
			}
		case "Answer":
			z.Answer, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Answer")
				return
			}
		case "Suggestion":
			z.Suggestion, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Suggestion")
				return
			}
		case "Correction":
			z.Correction, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Correction")
				return
			}
		case "NumberOfResults":
			z.NumberOfResults, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "NumberOfResults")
				return
			}
		case "EngineData":
			z.EngineData, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "EngineData")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LegacyResult) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 22
	// write "URL"
	err = en.Append(0xde, 0x0, 0x16, 0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "Template"
	err = en.Append(0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Template)
	if err != nil {
		err = msgp.WrapError(err, "Template")
		return
	}
	// write "Engine"
	err = en.Append(0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Engine)
	if err != nil {
		err = msgp.WrapError(err, "Engine")
		return
	}
	// write "ParsedURL"
	err = en.Append(0xa9, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.ParsedURL)
	if err != nil {
		err = msgp.WrapError(err, "ParsedURL")
		return
	}
	// write "Title"
	err = en.Append(0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "ImgSrc"
	err = en.Append(0xa6, 0x49, 0x6d, 0x67, 0x53, 0x72, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.ImgSrc)
	if err != nil {
		err = msgp.WrapError(err, "ImgSrc")
		return
	}
	// write "Thumbnail"
	err = en.Append(0xa9, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Thumbnail)
	if err != nil {
		err = msgp.WrapError(err, "Thumbnail")
		return
	}
	// write "Priority"
	err = en.Append(0xa8, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Priority)
	if err != nil {
		err = msgp.WrapError(err, "Priority")
		return
	}
	// write "Engines"
	err = en.Append(0xa7, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Engines)))
	if err != nil {
		err = msgp.WrapError(err, "Engines")
		return
	}
	for za0001 := range z.Engines {
		err = en.WriteString(z.Engines[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Engines", za0001)
			return
		}
	}
	// write "Positions"
	err = en.Append(0xa9, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Positions)))
	if err != nil {
		err = msgp.WrapError(err, "Positions")
		return
	}
	for za0002 := range z.Positions {
		err = en.WriteInt(z.Positions[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Positions", za0002)
			return
		}
	}
	// write "Score"
	err = en.Append(0xa5, 0x53, 0x63, 0x6f, 0x72, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Score)
	if err != nil {
		err = msgp.WrapError(err, "Score")
		return
	}
	// write "Category"
	err = en.Append(0xa8, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Category)
	if err != nil {
		err = msgp.WrapError(err, "Category")
		return
	}
	// write "PublishedDate"
	err = en.Append(0xad, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	if z.PublishedDate == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 1
		// write "Time"
		err = en.Append(0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteTime(z.PublishedDate.Time)
		if err != nil {
			err = msgp.WrapError(err, "PublishedDate", "Time")
			return
		}
	}
	// write "PubDate"
	err = en.Append(0xa7, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.PubDate)
	if err != nil {
		err = msgp.WrapError(err, "PubDate")
		return
	}
	// write "URLs"
	err = en.Append(0xa4, 0x55, 0x52, 0x4c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.URLs)))
	if err != nil {
		err = msgp.WrapError(err, "URLs")
		return
	}
	for za0003 := range z.URLs {
		// map header, size 2
		// write "Title"
		err = en.Append(0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.URLs[za0003].Title)
		if err != nil {
			err = msgp.WrapError(err, "URLs", za0003, "Title")
			return
		}
		// write "URL"
		err = en.Append(0xa3, 0x55, 0x52, 0x4c)
		if err != nil {
			return
		}
		err = en.WriteString(z.URLs[za0003].URL)
		if err != nil {
			err = msgp.WrapError(err, "URLs", za0003, "URL")
			return
		}
	}
	// write "Attributes"
	err = en.Append(0xaa, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Attributes)))
	if err != nil {
		err = msgp.WrapError(err, "Attributes")
		return
	}
	for za0004 := range z.Attributes {
		err = z.Attributes[za0004].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Attributes", za0004)
			return
		}
	}
	// write "Answer"
	err = en.Append(0xa6, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Answer)
	if err != nil {
		err = msgp.WrapError(err, "Answer")
		return
	}
	// write "Suggestion"
	err = en.Append(0xaa, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Suggestion)
	if err != nil {
		err = msgp.WrapError(err, "Suggestion")
		return
	}
	// write "Correction"
	err = en.Append(0xaa, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Correction)
	if err != nil {
		err = msgp.WrapError(err, "Correction")
		return
	}
	// write "NumberOfResults"
	err = en.Append(0xaf, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.NumberOfResults)
	if err != nil {
		err = msgp.WrapError(err, "NumberOfResults")
		return
	}
	// write "EngineData"
	err = en.Append(0xaa, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(z.EngineData)
	if err != nil {
		err = msgp.WrapError(err, "EngineData")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LegacyResult) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 22
	// string "URL"
	o = append(o, 0xde, 0x0, 0x16, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	// string "Template"
	o = append(o, 0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.Template)
	// string "Engine"
	o = append(o, 0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	o = msgp.AppendString(o, z.Engine)
	// string "ParsedURL"
	o = append(o, 0xa9, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.ParsedURL)
	// string "Title"
	o = append(o, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "ImgSrc"
	o = append(o, 0xa6, 0x49, 0x6d, 0x67, 0x53, 0x72, 0x63)
	o = msgp.AppendString(o, z.ImgSrc)
	// string "Thumbnail"
	o = append(o, 0xa9, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c)
	o = msgp.AppendString(o, z.Thumbnail)
	// string "Priority"
	o = append(o, 0xa8, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79)
	o = msgp.AppendString(o, z.Priority)
	// string "Engines"
	o = append(o, 0xa7, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Engines)))
	for za0001 := range z.Engines {
		o = msgp.AppendString(o, z.Engines[za0001])
	}
	// string "Positions"
	o = append(o, 0xa9, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Positions)))
	for za0002 := range z.Positions {
		o = msgp.AppendInt(o, z.Positions[za0002])
	}
	// string "Score"
	o = append(o, 0xa5, 0x53, 0x63, 0x6f, 0x72, 0x65)
	o = msgp.AppendFloat64(o, z.Score)
	// string "Category"
	o = append(o, 0xa8, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79)
	o = msgp.AppendString(o, z.Category)
	// string "PublishedDate"
	o = append(o, 0xad, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65)
	if z.PublishedDate == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 1
		// string "Time"
		o = append(o, 0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65)
		o = msgp.AppendTime(o, z.PublishedDate.Time)
	}
	// string "PubDate"
	o = append(o, 0xa7, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.PubDate)
	// string "URLs"
	o = append(o, 0xa4, 0x55, 0x52, 0x4c, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.URLs)))
	for za0003 := range z.URLs {
		// map header, size 2
		// string "Title"
		o = append(o, 0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
		o = msgp.AppendString(o, z.URLs[za0003].Title)
		// string "URL"
		o = append(o, 0xa3, 0x55, 0x52, 0x4c)
		o = msgp.AppendString(o, z.URLs[za0003].URL)
	}
	// string "Attributes"
	o = append(o, 0xaa, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Attributes)))
	for za0004 := range z.Attributes {
		o, err = z.Attributes[za0004].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Attributes", za0004)
			return
		}
	}
	// string "Answer"
	o = append(o, 0xa6, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72)
	o = msgp.AppendString(o, z.Answer)
	// string "Suggestion"
	o = append(o, 0xaa, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Suggestion)
	// string "Correction"
	o = append(o, 0xaa, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Correction)
	// string "NumberOfResults"
	o = append(o, 0xaf, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73)
	o = msgp.AppendInt(o, z.NumberOfResults)
	// string "EngineData"
	o = append(o, 0xaa, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendString(o, z.EngineData)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LegacyResult) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Template":
			z.Template, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Engine":
			z.Engine, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "ParsedURL":
			z.ParsedURL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ParsedURL")
				return
			}
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "ImgSrc":
			z.ImgSrc, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ImgSrc")
				return
			}
		case "Thumbnail":
			z.Thumbnail, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Thumbnail")
				return
			}
		case "Priority":
			z.Priority, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Priority")
				return
			}
		case "Engines":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Engines")
				return
			}
			if cap(z.Engines) >= int(zb0002) {
				z.Engines = (z.Engines)[:zb0002]
			} else {
				z.Engines = make([]string, zb0002)
			}
			for za0001 := range z.Engines {
				z.Engines[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Engines", za0001)
					return
				}
			}
		case "Positions":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Positions")
				return
			}
			if cap(z.Positions) >= int(zb0003) {
				z.Positions = (z.Positions)[:zb0003]
			} else {
				z.Positions = make([]int, zb0003)
			}
			for za0002 := range z.Positions {
				z.Positions[za0002], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Positions", za0002)
					return
				}
			}
		case "Score":
			z.Score, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Score")
				return
			}
		case "Category":
			z.Category, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Category")
				return
			}
		case "PublishedDate":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.PublishedDate = nil
			} else {
				if z.PublishedDate == nil {
					z.PublishedDate = new(Time)
				}
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PublishedDate")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "PublishedDate")
						return
					}
					switch msgp.UnsafeString(field) {
					case "Time":
						z.PublishedDate.Time, bts, err = msgp.ReadTimeBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate", "Time")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate")
							return
						}
					}
				}
			}
		case "PubDate":
			z.PubDate, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PubDate")
				return
			}
		case "URLs":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URLs")
				return
			}
			if cap(z.URLs) >= int(zb0005) {
				z.URLs = (z.URLs)[:zb0005]
			} else {
				z.URLs = make([]InfoboxURL, zb0005)
			}
			for za0003 := range z.URLs {
				var zb0006 uint32
				zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "URLs", za0003)
					return
				}
				for zb0006 > 0 {
					zb0006--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "URLs", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Title":
						z.URLs[za0003].Title, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0003, "Title")
							return
						}
					case "URL":
						z.URLs[za0003].URL, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0003, "URL")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "URLs", za0003)
							return
						}
					}
				}
			}
		case "Attributes":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Attributes")
				return
			}
			if cap(z.Attributes) >= int(zb0007) {
				z.Attributes = (z.Attributes)[:zb0007]
			} else {
				z.Attributes = make([]InfoboxAttribute, zb0007)
			}
			for za0004 := range z.Attributes {
				bts, err = z.Attributes[za0004].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Attributes", za0004)
					return
				}
			}
		case "Answer":
			z.Answer, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Answer")
				return
			}
		case "Suggestion":
			z.Suggestion, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Suggestion")
				return
			}
		case "Correction":
			z.Correction, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Correction")
				return
			}
		case "NumberOfResults":
			z.NumberOfResults, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NumberOfResults")
				return
			}
		case "EngineData":
			z.EngineData, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EngineData")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LegacyResult) Msgsize() (s int) {
	s = 3 + 4 + msgp.StringPrefixSize + len(z.URL) + 9 + msgp.StringPrefixSize + len(z.Template) + 7 + msgp.StringPrefixSize + len(z.Engine) + 10 + msgp.StringPrefixSize + len(z.ParsedURL) + 6 + msgp.StringPrefixSize + len(z.Title) + 8 + msgp.StringPrefixSize + len(z.Content) + 7 + msgp.StringPrefixSize + len(z.ImgSrc) + 10 + msgp.StringPrefixSize + len(z.Thumbnail) + 9 + msgp.StringPrefixSize + len(z.Priority) + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Engines {
		s += msgp.StringPrefixSize + len(z.Engines[za0001])
	}
	s += 10 + msgp.ArrayHeaderSize + (len(z.Positions) * (msgp.IntSize)) + 6 + msgp.Float64Size + 9 + msgp.StringPrefixSize + len(z.Category) + 14
	if z.PublishedDate == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 5 + msgp.TimeSize
	}
	s += 8 + msgp.StringPrefixSize + len(z.PubDate) + 5 + msgp.ArrayHeaderSize
	for za0003 := range z.URLs {
		s += 1 + 6 + msgp.StringPrefixSize + len(z.URLs[za0003].Title) + 4 + msgp.StringPrefixSize + len(z.URLs[za0003].URL)
	}
	s += 11 + msgp.ArrayHeaderSize
	for za0004 := range z.Attributes {
		s += z.Attributes[za0004].Msgsize()
	}
	s += 7 + msgp.StringPrefixSize + len(z.Answer) + 11 + msgp.StringPrefixSize + len(z.Suggestion) + 11 + msgp.StringPrefixSize + len(z.Correction) + 16 + msgp.IntSize + 11 + msgp.StringPrefixSize + len(z.EngineData)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Result) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Engine":
			z.Engine, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "ParsedURL":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ParsedURL")
				return
			}
			if zb0002 != uint32(6) {
				err = msgp.ArrayError{Wanted: uint32(6), Got: zb0002}
				return
			}
			for za0001 := range z.ParsedURL {
				z.ParsedURL[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ParsedURL", za0001)
					return
				}
			}
		case "Template":
			z.Template, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "ImgSrc":
			z.ImgSrc, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ImgSrc")
				return
			}
		case "IframeSrc":
			z.IframeSrc, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "IframeSrc")
				return
			}
		case "AudioSrc":
			z.AudioSrc, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AudioSrc")
				return
			}
		case "Thumbnail":
			z.Thumbnail, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Thumbnail")
				return
			}
		case "PublishedDate":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "PublishedDate")
					return
				}
				z.PublishedDate = nil
			} else {
				if z.PublishedDate == nil {
					z.PublishedDate = new(Time)
				}
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "PublishedDate")
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "PublishedDate")
						return
					}
					switch msgp.UnsafeString(field) {
					case "Time":
						z.PublishedDate.Time, err = dc.ReadTime()
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate", "Time")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate")
							return
						}
					}
				}
			}
		case "PubDate":
			z.PubDate, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PubDate")
				return
			}
		case "Length":
			z.Length, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Length")
				return
			}
		case "Views":
			z.Views, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Views")
				return
			}
		case "Author":
			z.Author, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Author")
				return
			}
		case "Metadata":
			z.Metadata, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		case "Priority":
			z.Priority, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Priority")
				return
			}
		case "Engines":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Engines")
				return
			}
			if cap(z.Engines) >= int(zb0004) {
				z.Engines = (z.Engines)[:zb0004]
			} else {
				z.Engines = make([]string, zb0004)
			}
			for za0002 := range z.Engines {
				z.Engines[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Engines", za0002)
					return
				}
			}
		case "OpenGroup":
			z.OpenGroup, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "OpenGroup")
				return
			}
		case "CloseGroup":
			z.CloseGroup, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "CloseGroup")
				return
			}
		case "Positions":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Positions")
				return
			}
			if cap(z.Positions) >= int(zb0005) {
				z.Positions = (z.Positions)[:zb0005]
			} else {
				z.Positions = make([]int, zb0005)
			}
			for za0003 := range z.Positions {
				z.Positions[za0003], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Positions", za0003)
					return
				}
			}
		case "Score":
			z.Score, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Score")
				return
			}
		case "Category":
			z.Category, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Category")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Result) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 23
	// write "URL"
	err = en.Append(0xde, 0x0, 0x17, 0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "Engine"
	err = en.Append(0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Engine)
	if err != nil {
		err = msgp.WrapError(err, "Engine")
		return
	}
	// write "ParsedURL"
	err = en.Append(0xa9, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(6))
	if err != nil {
		err = msgp.WrapError(err, "ParsedURL")
		return
	}
	for za0001 := range z.ParsedURL {
		err = en.WriteString(z.ParsedURL[za0001])
		if err != nil {
			err = msgp.WrapError(err, "ParsedURL", za0001)
			return
		}
	}
	// write "Template"
	err = en.Append(0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Template)
	if err != nil {
		err = msgp.WrapError(err, "Template")
		return
	}
	// write "Title"
	err = en.Append(0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "ImgSrc"
	err = en.Append(0xa6, 0x49, 0x6d, 0x67, 0x53, 0x72, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.ImgSrc)
	if err != nil {
		err = msgp.WrapError(err, "ImgSrc")
		return
	}
	// write "IframeSrc"
	err = en.Append(0xa9, 0x49, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x72, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.IframeSrc)
	if err != nil {
		err = msgp.WrapError(err, "IframeSrc")
		return
	}
	// write "AudioSrc"
	err = en.Append(0xa8, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x72, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.AudioSrc)
	if err != nil {
		err = msgp.WrapError(err, "AudioSrc")
		return
	}
	// write "Thumbnail"
	err = en.Append(0xa9, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Thumbnail)
	if err != nil {
		err = msgp.WrapError(err, "Thumbnail")
		return
	}
	// write "PublishedDate"
	err = en.Append(0xad, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	if z.PublishedDate == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 1
		// write "Time"
		err = en.Append(0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteTime(z.PublishedDate.Time)
		if err != nil {
			err = msgp.WrapError(err, "PublishedDate", "Time")
			return
		}
	}
	// write "PubDate"
	err = en.Append(0xa7, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.PubDate)
	if err != nil {
		err = msgp.WrapError(err, "PubDate")
		return
	}
	// write "Length"
	err = en.Append(0xa6, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Length)
	if err != nil {
		err = msgp.WrapError(err, "Length")
		return
	}
	// write "Views"
	err = en.Append(0xa5, 0x56, 0x69, 0x65, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Views)
	if err != nil {
		err = msgp.WrapError(err, "Views")
		return
	}
	// write "Author"
	err = en.Append(0xa6, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Author)
	if err != nil {
		err = msgp.WrapError(err, "Author")
		return
	}
	// write "Metadata"
	err = en.Append(0xa8, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(z.Metadata)
	if err != nil {
		err = msgp.WrapError(err, "Metadata")
		return
	}
	// write "Priority"
	err = en.Append(0xa8, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Priority)
	if err != nil {
		err = msgp.WrapError(err, "Priority")
		return
	}
	// write "Engines"
	err = en.Append(0xa7, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Engines)))
	if err != nil {
		err = msgp.WrapError(err, "Engines")
		return
	}
	for za0002 := range z.Engines {
		err = en.WriteString(z.Engines[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Engines", za0002)
			return
		}
	}
	// write "OpenGroup"
	err = en.Append(0xa9, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70)
	if err != nil {
		return
	}
	err = en.WriteBool(z.OpenGroup)
	if err != nil {
		err = msgp.WrapError(err, "OpenGroup")
		return
	}
	// write "CloseGroup"
	err = en.Append(0xaa, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70)
	if err != nil {
		return
	}
	err = en.WriteBool(z.CloseGroup)
	if err != nil {
		err = msgp.WrapError(err, "CloseGroup")
		return
	}
	// write "Positions"
	err = en.Append(0xa9, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Positions)))
	if err != nil {
		err = msgp.WrapError(err, "Positions")
		return
	}
	for za0003 := range z.Positions {
		err = en.WriteInt(z.Positions[za0003])
		if err != nil {
			err = msgp.WrapError(err, "Positions", za0003)
			return
		}
	}
	// write "Score"
	err = en.Append(0xa5, 0x53, 0x63, 0x6f, 0x72, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Score)
	if err != nil {
		err = msgp.WrapError(err, "Score")
		return
	}
	// write "Category"
	err = en.Append(0xa8, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Category)
	if err != nil {
		err = msgp.WrapError(err, "Category")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Result) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 23
	// string "URL"
	o = append(o, 0xde, 0x0, 0x17, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	// string "Engine"
	o = append(o, 0xa6, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65)
	o = msgp.AppendString(o, z.Engine)
	// string "ParsedURL"
	o = append(o, 0xa9, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x55, 0x52, 0x4c)
	o = msgp.AppendArrayHeader(o, uint32(6))
	for za0001 := range z.ParsedURL {
		o = msgp.AppendString(o, z.ParsedURL[za0001])
	}
	// string "Template"
	o = append(o, 0xa8, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.Template)
	// string "Title"
	o = append(o, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "ImgSrc"
	o = append(o, 0xa6, 0x49, 0x6d, 0x67, 0x53, 0x72, 0x63)
	o = msgp.AppendString(o, z.ImgSrc)
	// string "IframeSrc"
	o = append(o, 0xa9, 0x49, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x72, 0x63)
	o = msgp.AppendString(o, z.IframeSrc)
	// string "AudioSrc"
	o = append(o, 0xa8, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x72, 0x63)
	o = msgp.AppendString(o, z.AudioSrc)
	// string "Thumbnail"
	o = append(o, 0xa9, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c)
	o = msgp.AppendString(o, z.Thumbnail)
	// string "PublishedDate"
	o = append(o, 0xad, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65)
	if z.PublishedDate == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 1
		// string "Time"
		o = append(o, 0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65)
		o = msgp.AppendTime(o, z.PublishedDate.Time)
	}
	// string "PubDate"
	o = append(o, 0xa7, 0x50, 0x75, 0x62, 0x44, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.PubDate)
	// string "Length"
	o = append(o, 0xa6, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	o = msgp.AppendString(o, z.Length)
	// string "Views"
	o = append(o, 0xa5, 0x56, 0x69, 0x65, 0x77, 0x73)
	o = msgp.AppendString(o, z.Views)
	// string "Author"
	o = append(o, 0xa6, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72)
	o = msgp.AppendString(o, z.Author)
	// string "Metadata"
	o = append(o, 0xa8, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendString(o, z.Metadata)
	// string "Priority"
	o = append(o, 0xa8, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79)
	o = msgp.AppendString(o, z.Priority)
	// string "Engines"
	o = append(o, 0xa7, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Engines)))
	for za0002 := range z.Engines {
		o = msgp.AppendString(o, z.Engines[za0002])
	}
	// string "OpenGroup"
	o = append(o, 0xa9, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70)
	o = msgp.AppendBool(o, z.OpenGroup)
	// string "CloseGroup"
	o = append(o, 0xaa, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70)
	o = msgp.AppendBool(o, z.CloseGroup)
	// string "Positions"
	o = append(o, 0xa9, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Positions)))
	for za0003 := range z.Positions {
		o = msgp.AppendInt(o, z.Positions[za0003])
	}
	// string "Score"
	o = append(o, 0xa5, 0x53, 0x63, 0x6f, 0x72, 0x65)
	o = msgp.AppendFloat64(o, z.Score)
	// string "Category"
	o = append(o, 0xa8, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79)
	o = msgp.AppendString(o, z.Category)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Result) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Engine":
			z.Engine, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Engine")
				return
			}
		case "ParsedURL":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ParsedURL")
				return
			}
			if zb0002 != uint32(6) {
				err = msgp.ArrayError{Wanted: uint32(6), Got: zb0002}
				return
			}
			for za0001 := range z.ParsedURL {
				z.ParsedURL[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ParsedURL", za0001)
					return
				}
			}
		case "Template":
			z.Template, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Template")
				return
			}
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "ImgSrc":
			z.ImgSrc, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ImgSrc")
				return
			}
		case "IframeSrc":
			z.IframeSrc, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IframeSrc")
				return
			}
		case "AudioSrc":
			z.AudioSrc, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AudioSrc")
				return
			}
		case "Thumbnail":
			z.Thumbnail, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Thumbnail")
				return
			}
		case "PublishedDate":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.PublishedDate = nil
			} else {
				if z.PublishedDate == nil {
					z.PublishedDate = new(Time)
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PublishedDate")
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "PublishedDate")
						return
					}
					switch msgp.UnsafeString(field) {
					case "Time":
						z.PublishedDate.Time, bts, err = msgp.ReadTimeBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate", "Time")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "PublishedDate")
							return
						}
					}
				}
			}
		case "PubDate":
			z.PubDate, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PubDate")
				return
			}
		case "Length":
			z.Length, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Length")
				return
			}
		case "Views":
			z.Views, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Views")
				return
			}
		case "Author":
			z.Author, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Author")
				return
			}
		case "Metadata":
			z.Metadata, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		case "Priority":
			z.Priority, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Priority")
				return
			}
		case "Engines":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Engines")
				return
			}
			if cap(z.Engines) >= int(zb0004) {
				z.Engines = (z.Engines)[:zb0004]
			} else {
				z.Engines = make([]string, zb0004)
			}
			for za0002 := range z.Engines {
				z.Engines[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Engines", za0002)
					return
				}
			}
		case "OpenGroup":
			z.OpenGroup, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OpenGroup")
				return
			}
		case "CloseGroup":
			z.CloseGroup, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CloseGroup")
				return
			}
		case "Positions":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Positions")
				return
			}
			if cap(z.Positions) >= int(zb0005) {
				z.Positions = (z.Positions)[:zb0005]
			} else {
				z.Positions = make([]int, zb0005)
			}
			for za0003 := range z.Positions {
				z.Positions[za0003], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Positions", za0003)
					return
				}
			}
		case "Score":
			z.Score, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Score")
				return
			}
		case "Category":
			z.Category, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Category")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Result) Msgsize() (s int) {
	s = 3 + 4 + msgp.StringPrefixSize + len(z.URL) + 7 + msgp.StringPrefixSize + len(z.Engine) + 10 + msgp.ArrayHeaderSize
	for za0001 := range z.ParsedURL {
		s += msgp.StringPrefixSize + len(z.ParsedURL[za0001])
	}
	s += 9 + msgp.StringPrefixSize + len(z.Template) + 6 + msgp.StringPrefixSize + len(z.Title) + 8 + msgp.StringPrefixSize + len(z.Content) + 7 + msgp.StringPrefixSize + len(z.ImgSrc) + 10 + msgp.StringPrefixSize + len(z.IframeSrc) + 9 + msgp.StringPrefixSize + len(z.AudioSrc) + 10 + msgp.StringPrefixSize + len(z.Thumbnail) + 14
	if z.PublishedDate == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 5 + msgp.TimeSize
	}
	s += 8 + msgp.StringPrefixSize + len(z.PubDate) + 7 + msgp.StringPrefixSize + len(z.Length) + 6 + msgp.StringPrefixSize + len(z.Views) + 7 + msgp.StringPrefixSize + len(z.Author) + 9 + msgp.StringPrefixSize + len(z.Metadata) + 9 + msgp.StringPrefixSize + len(z.Priority) + 8 + msgp.ArrayHeaderSize
	for za0002 := range z.Engines {
		s += msgp.StringPrefixSize + len(z.Engines[za0002])
	}
	s += 10 + msgp.BoolSize + 11 + msgp.BoolSize + 10 + msgp.ArrayHeaderSize + (len(z.Positions) * (msgp.IntSize)) + 6 + msgp.Float64Size + 9 + msgp.StringPrefixSize + len(z.Category)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SearchResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Query":
			z.Query, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Query")
				return
			}
		case "NumberOfResults":
			z.NumberOfResults, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "NumberOfResults")
				return
			}
		case "Results":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Results")
				return
			}
			if cap(z.Results) >= int(zb0002) {
				z.Results = (z.Results)[:zb0002]
			} else {
				z.Results = make([]Result, zb0002)
			}
			for za0001 := range z.Results {
				err = z.Results[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Results", za0001)
					return
				}
			}
		case "Answers":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Answers")
				return
			}
			if cap(z.Answers) >= int(zb0003) {
				z.Answers = (z.Answers)[:zb0003]
			} else {
				z.Answers = make([]Answer, zb0003)
			}
			for za0002 := range z.Answers {
				err = z.Answers[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Answers", za0002)
					return
				}
			}
		case "Corrections":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Corrections")
				return
			}
			if cap(z.Corrections) >= int(zb0004) {
				z.Corrections = (z.Corrections)[:zb0004]
			} else {
				z.Corrections = make([]string, zb0004)
			}
			for za0003 := range z.Corrections {
				z.Corrections[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Corrections", za0003)
					return
				}
			}
		case "Infoboxes":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Infoboxes")
				return
			}
			if cap(z.Infoboxes) >= int(zb0005) {
				z.Infoboxes = (z.Infoboxes)[:zb0005]
			} else {
				z.Infoboxes = make([]Infobox, zb0005)
			}
			for za0004 := range z.Infoboxes {
				err = z.Infoboxes[za0004].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Infoboxes", za0004)
					return
				}
			}
		case "Suggestions":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Suggestions")
				return
			}
			if cap(z.Suggestions) >= int(zb0006) {
				z.Suggestions = (z.Suggestions)[:zb0006]
			} else {
				z.Suggestions = make([]string, zb0006)
			}
			for za0005 := range z.Suggestions {
				z.Suggestions[za0005], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Suggestions", za0005)
					return
				}
			}
		case "UnresponsiveEngines":
			var zb0007 uint32
			zb0007, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "UnresponsiveEngines")
				return
			}
			if cap(z.UnresponsiveEngines) >= int(zb0007) {
				z.UnresponsiveEngines = (z.UnresponsiveEngines)[:zb0007]
			} else {
				z.UnresponsiveEngines = make([]EngineError, zb0007)
			}
			for za0006 := range z.UnresponsiveEngines {
				var zb0008 uint32
				zb0008, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "UnresponsiveEngines", za0006)
					return
				}
				if cap(z.UnresponsiveEngines[za0006]) >= int(zb0008) {
					z.UnresponsiveEngines[za0006] = (z.UnresponsiveEngines[za0006])[:zb0008]
				} else {
					z.UnresponsiveEngines[za0006] = make(EngineError, zb0008)
				}
				for za0007 := range z.UnresponsiveEngines[za0006] {
					z.UnresponsiveEngines[za0006][za0007], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "UnresponsiveEngines", za0006, za0007)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SearchResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "Query"
	err = en.Append(0x88, 0xa5, 0x51, 0x75, 0x65, 0x72, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Query)
	if err != nil {
		err = msgp.WrapError(err, "Query")
		return
	}
	// write "NumberOfResults"
	err = en.Append(0xaf, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.NumberOfResults)
	if err != nil {
		err = msgp.WrapError(err, "NumberOfResults")
		return
	}
	// write "Results"
	err = en.Append(0xa7, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Results)))
	if err != nil {
		err = msgp.WrapError(err, "Results")
		return
	}
	for za0001 := range z.Results {
		err = z.Results[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Results", za0001)
			return
		}
	}
	// write "Answers"
	err = en.Append(0xa7, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Answers)))
	if err != nil {
		err = msgp.WrapError(err, "Answers")
		return
	}
	for za0002 := range z.Answers {
		err = z.Answers[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Answers", za0002)
			return
		}
	}
	// write "Corrections"
	err = en.Append(0xab, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Corrections)))
	if err != nil {
		err = msgp.WrapError(err, "Corrections")
		return
	}
	for za0003 := range z.Corrections {
		err = en.WriteString(z.Corrections[za0003])
		if err != nil {
			err = msgp.WrapError(err, "Corrections", za0003)
			return
		}
	}
	// write "Infoboxes"
	err = en.Append(0xa9, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x78, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Infoboxes)))
	if err != nil {
		err = msgp.WrapError(err, "Infoboxes")
		return
	}
	for za0004 := range z.Infoboxes {
		err = z.Infoboxes[za0004].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Infoboxes", za0004)
			return
		}
	}
	// write "Suggestions"
	err = en.Append(0xab, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Suggestions)))
	if err != nil {
		err = msgp.WrapError(err, "Suggestions")
		return
	}
	for za0005 := range z.Suggestions {
		err = en.WriteString(z.Suggestions[za0005])
		if err != nil {
			err = msgp.WrapError(err, "Suggestions", za0005)
			return
		}
	}
	// write "UnresponsiveEngines"
	err = en.Append(0xb3, 0x55, 0x6e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.UnresponsiveEngines)))
	if err != nil {
		err = msgp.WrapError(err, "UnresponsiveEngines")
		return
	}
	for za0006 := range z.UnresponsiveEngines {
		err = en.WriteArrayHeader(uint32(len(z.UnresponsiveEngines[za0006])))
		if err != nil {
			err = msgp.WrapError(err, "UnresponsiveEngines", za0006)
			return
		}
		for za0007 := range z.UnresponsiveEngines[za0006] {
			err = en.WriteString(z.UnresponsiveEngines[za0006][za0007])
			if err != nil {
				err = msgp.WrapError(err, "UnresponsiveEngines", za0006, za0007)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SearchResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "Query"
	o = append(o, 0x88, 0xa5, 0x51, 0x75, 0x65, 0x72, 0x79)
	o = msgp.AppendString(o, z.Query)
	// string "NumberOfResults"
	o = append(o, 0xaf, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73)
	o = msgp.AppendInt(o, z.NumberOfResults)
	// string "Results"
	o = append(o, 0xa7, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Results)))
	for za0001 := range z.Results {
		o, err = z.Results[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Results", za0001)
			return
		}
	}
	// string "Answers"
	o = append(o, 0xa7, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Answers)))
	for za0002 := range z.Answers {
		o, err = z.Answers[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Answers", za0002)
			return
		}
	}
	// string "Corrections"
	o = append(o, 0xab, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Corrections)))
	for za0003 := range z.Corrections {
		o = msgp.AppendString(o, z.Corrections[za0003])
	}
	// string "Infoboxes"
	o = append(o, 0xa9, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x6f, 0x78, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Infoboxes)))
	for za0004 := range z.Infoboxes {
		o, err = z.Infoboxes[za0004].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Infoboxes", za0004)
			return
		}
	}
	// string "Suggestions"
	o = append(o, 0xab, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Suggestions)))
	for za0005 := range z.Suggestions {
		o = msgp.AppendString(o, z.Suggestions[za0005])
	}
	// string "UnresponsiveEngines"
	o = append(o, 0xb3, 0x55, 0x6e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.UnresponsiveEngines)))
	for za0006 := range z.UnresponsiveEngines {
		o = msgp.AppendArrayHeader(o, uint32(len(z.UnresponsiveEngines[za0006])))
		for za0007 := range z.UnresponsiveEngines[za0006] {
			o = msgp.AppendString(o, z.UnresponsiveEngines[za0006][za0007])
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SearchResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Query":
			z.Query, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Query")
				return
			}
		case "NumberOfResults":
			z.NumberOfResults, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NumberOfResults")
				return
			}
		case "Results":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Results")
				return
			}
			if cap(z.Results) >= int(zb0002) {
				z.Results = (z.Results)[:zb0002]
			} else {
				z.Results = make([]Result, zb0002)
			}
			for za0001 := range z.Results {
				bts, err = z.Results[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Results", za0001)
					return
				}
			}
		case "Answers":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Answers")
				return
			}
			if cap(z.Answers) >= int(zb0003) {
				z.Answers = (z.Answers)[:zb0003]
			} else {
				z.Answers = make([]Answer, zb0003)
			}
			for za0002 := range z.Answers {
				bts, err = z.Answers[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Answers", za0002)
					return
				}
			}
		case "Corrections":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Corrections")
				return
			}
			if cap(z.Corrections) >= int(zb0004) {
				z.Corrections = (z.Corrections)[:zb0004]
			} else {
				z.Corrections = make([]string, zb0004)
			}
			for za0003 := range z.Corrections {
				z.Corrections[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Corrections", za0003)
					return
				}
			}
		case "Infoboxes":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Infoboxes")
				return
			}
			if cap(z.Infoboxes) >= int(zb0005) {
				z.Infoboxes = (z.Infoboxes)[:zb0005]
			} else {
				z.Infoboxes = make([]Infobox, zb0005)
			}
			for za0004 := range z.Infoboxes {
				bts, err = z.Infoboxes[za0004].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Infoboxes", za0004)
					return
				}
			}
		case "Suggestions":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Suggestions")
				return
			}
			if cap(z.Suggestions) >= int(zb0006) {
				z.Suggestions = (z.Suggestions)[:zb0006]
			} else {
				z.Suggestions = make([]string, zb0006)
			}
			for za0005 := range z.Suggestions {
				z.Suggestions[za0005], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Suggestions", za0005)
					return
				}
			}
		case "UnresponsiveEngines":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UnresponsiveEngines")
				return
			}
			if cap(z.UnresponsiveEngines) >= int(zb0007) {
				z.UnresponsiveEngines = (z.UnresponsiveEngines)[:zb0007]
			} else {
				z.UnresponsiveEngines = make([]EngineError, zb0007)
			}
			for za0006 := range z.UnresponsiveEngines {
				var zb0008 uint32
				zb0008, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "UnresponsiveEngines", za0006)
					return
				}
				if cap(z.UnresponsiveEngines[za0006]) >= int(zb0008) {
					z.UnresponsiveEngines[za0006] = (z.UnresponsiveEngines[za0006])[:zb0008]
				} else {
					z.UnresponsiveEngines[za0006] = make(EngineError, zb0008)
				}
				for za0007 := range z.UnresponsiveEngines[za0006] {
					z.UnresponsiveEngines[za0006][za0007], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "UnresponsiveEngines", za0006, za0007)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SearchResponse) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Query) + 16 + msgp.IntSize + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Results {
		s += z.Results[za0001].Msgsize()
	}
	s += 8 + msgp.ArrayHeaderSize
	for za0002 := range z.Answers {
		s += z.Answers[za0002].Msgsize()
	}
	s += 12 + msgp.ArrayHeaderSize
	for za0003 := range z.Corrections {
		s += msgp.StringPrefixSize + len(z.Corrections[za0003])
	}
	s += 10 + msgp.ArrayHeaderSize
	for za0004 := range z.Infoboxes {
		s += z.Infoboxes[za0004].Msgsize()
	}
	s += 12 + msgp.ArrayHeaderSize
	for za0005 := range z.Suggestions {
		s += msgp.StringPrefixSize + len(z.Suggestions[za0005])
	}
	s += 20 + msgp.ArrayHeaderSize
	for za0006 := range z.UnresponsiveEngines {
		s += msgp.ArrayHeaderSize
		for za0007 := range z.UnresponsiveEngines[za0006] {
			s += msgp.StringPrefixSize + len(z.UnresponsiveEngines[za0006][za0007])
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Time) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Time":
			z.Time, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Time) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Time"
	err = en.Append(0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Time)
	if err != nil {
		err = msgp.WrapError(err, "Time")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Time) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Time"
	o = append(o, 0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.Time)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Time) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Time":
			z.Time, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Time) Msgsize() (s int) {
	s = 1 + 5 + msgp.TimeSize
	return
}
