// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const deleteOld = `-- name: DeleteOld :exec
DELETE FROM cache WHERE key like ? and created_at < ?
`

type DeleteOldParams struct {
	Key       string
	CreatedAt time.Time
}

func (q *Queries) DeleteOld(ctx context.Context, arg DeleteOldParams) error {
	_, err := q.db.ExecContext(ctx, deleteOld, arg.Key, arg.CreatedAt)
	return err
}

const getCache = `-- name: GetCache :one
SELECT data, created_at FROM cache
WHERE key = ? LIMIT 1
`

type GetCacheRow struct {
	Data      []byte
	CreatedAt time.Time
}

func (q *Queries) GetCache(ctx context.Context, key string) (GetCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getCache, key)
	var i GetCacheRow
	err := row.Scan(&i.Data, &i.CreatedAt)
	return i, err
}

const insertCache = `-- name: InsertCache :exec
INSERT INTO cache (key, data)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET
    data = excluded.data,
    created_at = CURRENT_TIMESTAMP
`

type InsertCacheParams struct {
	Key  string
	Data []byte
}

func (q *Queries) InsertCache(ctx context.Context, arg InsertCacheParams) error {
	_, err := q.db.ExecContext(ctx, insertCache, arg.Key, arg.Data)
	return err
}
