// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const deleteOld = `-- name: DeleteOld :exec
DELETE FROM cache WHERE key like ? and expires <= ?
`

type DeleteOldParams struct {
	Key     string
	Expires time.Time
}

func (q *Queries) DeleteOld(ctx context.Context, arg DeleteOldParams) error {
	_, err := q.db.ExecContext(ctx, deleteOld, arg.Key, arg.Expires)
	return err
}

const getCache = `-- name: GetCache :one
SELECT data, expires FROM cache
WHERE key = ? LIMIT 1
`

type GetCacheRow struct {
	Data    []byte
	Expires time.Time
}

func (q *Queries) GetCache(ctx context.Context, key string) (GetCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getCache, key)
	var i GetCacheRow
	err := row.Scan(&i.Data, &i.Expires)
	return i, err
}

const insertCache = `-- name: InsertCache :exec
INSERT INTO cache (key, data, expires)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    data = excluded.data,
    expires = excluded.expires
`

type InsertCacheParams struct {
	Key     string
	Data    []byte
	Expires time.Time
}

func (q *Queries) InsertCache(ctx context.Context, arg InsertCacheParams) error {
	_, err := q.db.ExecContext(ctx, insertCache, arg.Key, arg.Data, arg.Expires)
	return err
}
